#!/usr/bin/env python3
"""
accuracy_to_tex.py -- build the LaTeX accuracy/linearity table
(results.tex \\label{tab:accuracy_linearity}, "Table 1") from accuracy_table.xlsx
written by Diameter_Figs.m.

Workflow
--------
    1. Run Diameter_Figs.m with save_tables = 1  -> tables/accuracy_table.xlsx
    2. (optional) hand-edit accuracy_table.xlsx
    3. python accuracy_to_tex.py                  -> tables/accuracy_table.tex

The .tex reproduces the manuscript table: slope (m), R^2 and CoV for each method
(BW-1..5, w_{1/e^2,G}, FWHM_GG, w_{1/e^2,GG}) x projection (MIP / MeIP), across
Pre / Peak / Post phases. Values are set bold per the manuscript's rules:
    slope  bold if 0.9 <= m <= 1.1
    R^2    bold if R^2 >= 0.90
    CoV    bold if CoV <= 0.10

Spreadsheet layout (written by MATLAB): columns Metric, Phase, then the 16
value columns in the fixed order below. Requires pandas + openpyxl. LaTeX side
needs \\resizebox (graphicx) -- already loaded by the Optica template.
"""
import argparse
import math
import os
import sys

import pandas as pd

# fixed value-column order (method x projection), matching Diameter_Figs.m
VALCOLS = [
    "BW1_MIP", "BW1_MeIP", "BW2_MIP", "BW2_MeIP", "BW3_MIP", "BW3_MeIP",
    "BW4_MIP", "BW4_MeIP", "BW5_MIP", "BW5_MeIP", "G_MIP", "G_MeIP",
    "FWHMGG_MIP", "FWHMGG_MeIP", "GGe2_MIP", "GGe2_MeIP",
]

GROUP_HEADER = (
    r" & \multicolumn{2}{c|}{\textbf{BW-1}} & \multicolumn{2}{c|}{\textbf{BW-2}} "
    r"& \multicolumn{2}{c|}{\textbf{BW-3}} & \multicolumn{2}{c|}{\textbf{BW-4}} "
    r"& \multicolumn{2}{c||}{\textbf{BW-5}} "
    r"& \multicolumn{2}{c|}{\textbf{$w_{1/e^2,\,\mathrm{G}}$}} "
    r"& \multicolumn{2}{c|}{\textbf{$\mathrm{FWHM}_{\mathrm{GG}}$}} "
    r"& \multicolumn{2}{c}{\textbf{$w_{1/e^2,\,\mathrm{GG}}$}} \\"
)
SUB_HEADER = " & " + " & ".join(["MIP", "MeIP"] * 8) + r" \\"

CAPTION = (
    r"Summary of slope ($m$), coefficient of determination ($R^2$), and "
    r"coefficient of variation (CoV) for all diameter measurement methods across "
    r"pre-contrast, peak contrast, and post-contrast conditions. Methods are grouped "
    r"as binary mask based and model-based. Bold values indicate slope agreement "
    r"within 10\% of unity ($0.9 \leq m \leq 1.1$), strong linearity "
    r"($R^2 \geq 0.90$), or high precision ($\mathrm{CoV} \leq 0.10$)."
)

BLOCKS = [  # (Metric key in the spreadsheet, block sub-header)
    ("Slope", r"\textit{Slope ($m$)}"),
    ("R2",    r"\textit{Coefficient of determination ($R^2$)}"),
    ("CoV",   r"\textit{Coefficient of variation (CoV)}"),
]
PHASE_ORDER = ["Pre", "Peak", "Post"]


def is_bold(metric, v):
    if math.isnan(v):
        return False
    if metric == "Slope":
        return 0.9 <= v <= 1.1
    if metric == "R2":
        return v >= 0.90
    if metric == "CoV":
        return v <= 0.10
    return False


def fmt(metric, v):
    if math.isnan(v):
        return ""
    s = f"{v:.2f}"
    return r"\textbf{" + s + "}" if is_bold(metric, v) else s


def build_tex(df, label="tab:accuracy_linearity"):
    L = []
    L.append(r"% Auto-generated by tables/accuracy_to_tex.py -- edit accuracy_table.xlsx and re-run.")
    L.append(r"\begin{table}[htbp]")
    L.append(r"\setlength{\abovecaptionskip}{4pt}\setlength{\belowcaptionskip}{2pt}")
    L.append(r"\caption{" + CAPTION + r"}")
    L.append(r"\label{" + label + r"}")
    L.append(r"\centering")
    L.append(r"\resizebox{\textwidth}{!}{%")
    L.append(r"\begin{tabular}{l c c | c c | c c | c c | c c || c c | c c | c c}")
    L.append(r"\hline")
    L.append(GROUP_HEADER)
    L.append(SUB_HEADER)

    for key, header in BLOCKS:
        L.append(r"\hline")
        L.append(r"\multicolumn{17}{l}{" + header + r"} \\")
        L.append(r"\hline")
        sub = df[df["Metric"].astype(str) == key]
        for ph in PHASE_ORDER:
            row = sub[sub["Phase"].astype(str) == ph]
            if row.empty:
                continue
            rec = row.iloc[0]
            cells = [fmt(key, float(rec[c])) for c in VALCOLS]
            L.append(ph + " & " + " & ".join(cells) + r" \\")

    L.append(r"\hline")
    L.append(r"\end{tabular}%")
    L.append(r"}")
    L.append(r"\end{table}")
    return "\n".join(L) + "\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description="Build the LaTeX accuracy/linearity table from accuracy_table.xlsx.")
    ap.add_argument("-i", "--input", default=os.path.join(here, "accuracy_table.xlsx"))
    ap.add_argument("-o", "--output", default=os.path.join(here, "accuracy_table.tex"))
    ap.add_argument("--label", default="tab:accuracy_linearity")
    a = ap.parse_args()

    inp = a.input
    if not os.path.exists(inp):
        csv = os.path.splitext(inp)[0] + ".csv"
        if os.path.exists(csv):
            inp = csv
        else:
            sys.exit(f"Input not found: {inp}\n"
                     f"Run Diameter_Figs.m with save_tables = 1 first.")

    df = pd.read_csv(inp) if inp.lower().endswith(".csv") else pd.read_excel(inp)
    with open(a.output, "w", encoding="utf-8") as fh:
        fh.write(build_tex(df, a.label))
    print(f"Wrote {a.output}  ({len(df)} rows, source: {os.path.basename(inp)})")


if __name__ == "__main__":
    main()
