#!/usr/bin/env python3
"""
xlsx_to_tex.py -- build the LaTeX flicker table (results.tex \\label{tab:flicker},
"Table 2") from flicker_table.xlsx written by Diameter_Figs_Stim.m.

Workflow
--------
    1. Run Diameter_Figs_Stim.m with save_tables = 1  -> tables/flicker_table.xlsx
    2. (optional) hand-edit flicker_table.xlsx in Excel
    3. python xlsx_to_tex.py                           -> tables/flicker_table.tex

The generated .tex reproduces the manuscript's flicker table exactly: per vessel,
diameter change dd (%) and correlation rho for Gaussian / GG / Binarised, plus
intensity change dI (%); statistically significant values are set bold with
superscript stars, followed by an Overall-rho row. It is a drop-in replacement
for the hand-coded table in results.tex (same \\label{tab:flicker}).

Significance is driven by the companion "*_p" columns:
    dd  significance  <- G_dd_p / GG_dd_p / BW_dd_p   (paired t-test)
    rho significance  <- G_rho_p / GG_rho_p / BW_rho_p (correlation p)
    dI  significance  <- I_dI_p                        (paired t-test)

Requires: pandas + openpyxl (pip install pandas openpyxl). LaTeX side needs no
special packages (plain tabular with \\hline / \\multicolumn).
"""
import argparse
import math
import os
import sys

import pandas as pd


def isnan(v):
    return v is None or (isinstance(v, float) and math.isnan(v))


def stars(p):
    if isnan(p):
        return ""
    if p < 0.001:
        return "***"
    if p < 0.01:
        return "**"
    if p < 0.05:
        return "*"
    return ""


def cell(val, p, pct=False, dec=2):
    """One math-mode table cell; bold + superscript stars when significant."""
    if isnan(val):
        return ""
    num = f"{val:+.1f}" if pct else f"{val:.{dec}f}"
    s = stars(p)
    if s:
        return r"$\mathbf{" + num + r"}^{" + s + r"}$"
    return r"$" + num + r"$"


CAPTION = (
    r"Flicker stimulation results. $\Delta d$: diameter change (\%); "
    r"$\rho$: Correlation between diameter and angiogram intensity; "
    r"$\Delta I$: intensity change (\%). Statistically significant values "
    r"are bold ($^{*}p < 0.05$, $^{**}p < 0.01$, $^{***}p < 0.001$)."
)


def build_tex(df, label="tab:flicker"):
    L = []
    L.append(r"% Auto-generated by tables/xlsx_to_tex.py -- edit flicker_table.xlsx and re-run.")
    L.append(r"\begin{table}[htbp]")
    L.append(r"\caption{" + CAPTION + r"}")
    L.append(r"\label{" + label + r"}")
    L.append(r"\centering")
    L.append(r"\setlength{\abovecaptionskip}{2pt}\setlength{\belowcaptionskip}{2pt}")
    L.append(r"\footnotesize")
    L.append(r"\begin{tabular}{l | c c | c c | c c | c}")
    L.append(r"\hline")
    L.append(r" & \multicolumn{2}{c|}{\textbf{Gaussian}} & \multicolumn{2}{c|}{\textbf{GG}} "
             r"& \multicolumn{2}{c|}{\textbf{Binarised}} & \textbf{Intensity} \\")
    L.append(r" & $\Delta d$ (\%) & $\rho$ & $\Delta d$ (\%) & $\rho$ & $\Delta d$ (\%) & $\rho$ "
             r"& $\Delta I$ (\%) \\")
    L.append(r"\hline")

    overall = None
    for _, r in df.iterrows():
        lab = str(r["Label"]).strip()
        if lab.lower().startswith("overall"):
            overall = r
            continue
        cells = [
            lab,
            cell(r["G_dd"],  r["G_dd_p"],  pct=True),   cell(r["G_rho"],  r["G_rho_p"],  dec=2),
            cell(r["GG_dd"], r["GG_dd_p"], pct=True),   cell(r["GG_rho"], r["GG_rho_p"], dec=2),
            cell(r["BW_dd"], r["BW_dd_p"], pct=True),   cell(r["BW_rho"], r["BW_rho_p"], dec=2),
            cell(r["I_dI"],  r["I_dI_p"],  pct=True),
        ]
        L.append(" & ".join(cells) + r" \\")

    if overall is not None:
        def o(v):
            return "" if isnan(v) else rf"${v:.3f}$"
        L.append(r"\hline")
        L.append(r"Overall $\rho$ & & " + o(overall["G_rho"]) + r" & & "
                 + o(overall["GG_rho"]) + r" & & " + o(overall["BW_rho"]) + r" \\")

    L.append(r"\hline")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")
    return "\n".join(L) + "\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description="Build the LaTeX flicker table from flicker_table.xlsx.")
    ap.add_argument("-i", "--input", default=os.path.join(here, "flicker_table.xlsx"))
    ap.add_argument("-o", "--output", default=os.path.join(here, "flicker_table.tex"))
    ap.add_argument("--label", default="tab:flicker")
    a = ap.parse_args()

    inp = a.input
    if not os.path.exists(inp):
        csv = os.path.splitext(inp)[0] + ".csv"
        if os.path.exists(csv):
            inp = csv
        else:
            sys.exit(f"Input not found: {inp}\n"
                     f"Run Diameter_Figs_Stim.m with save_tables = 1 first.")

    df = pd.read_csv(inp) if inp.lower().endswith(".csv") else pd.read_excel(inp)
    with open(a.output, "w", encoding="utf-8") as fh:
        fh.write(build_tex(df, a.label))
    print(f"Wrote {a.output}  ({len(df)} rows, source: {os.path.basename(inp)})")


if __name__ == "__main__":
    main()
